version: '3'
services:
  mmrelayapp:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: mmrelayapp:latest
    container_name: mmrelay-app
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - mesh_volume:/home/mesh
    networks:
      - mesh_net
    command: sh -c 'echo "export PATH=/home/mesh/.local/bin:\$PATH" >> /home/mesh/.bashrc' 
    entrypoint: ["sh", "-c", "sleep 30 && python app/main.py"]

  mmrelaynode:
    build:
      context: .
      dockerfile: Dockerfile_node
    image: mmrelaynode:latest
    container_name: mmrelay-node
    restart: unless-stopped
    user: 1000:1000
    networks:
      - mesh_net
        #   volumes:
        # - mesh_volume:/home/mesh
    ports:
      - 4403:4403
    entrypoint: ["sh", "-cx", "/usr/bin/meshtasticd -d /home/mesh --hwid '12345'"] #change to your own hardware id

networks:
  mesh_net:
volumes:
  mesh_volume:
