version: "3"
services:
  mmrelaynode:
    build: node
    image: mmrelaynode:latest
    container_name: mmrelay-node
    restart: unless-stopped

    volumes:
      - mesh:/home/mesh
    ports:
      - "4403:4403"
    networks:
      - mesh
    entrypoint: ["sh", "-c", "run"]

  mmrelayapp:
    build: app
    image: mmrelayapp:latest
    container_name: mmrelay-app
    restart: unless-stopped
    depends_on:
      - mmrelaynode
    volumes:
      - mesh:/home/mesh
    networks:
      - mesh    
    command: ["sleep 30"]
    entrypoint: ["python3", "main.py"]

volumes:
  mesh:

networks:
  mesh:
