version: '3'
services:
  mmrelaynode:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: mmrelayapp:latest
    container_name: mmrelay-app
    restart: unless-stopped
    command: sh -c 'mv /home/mesh/.* /tmp/'
    user: 1000:1000
    volumes:
      - mesh_volume:/home/mesh
      - ./meshtastic-matrix-relay:/home/mesh/app
      - ./config.yaml:/home/mesh/app/config.yaml
    networks:
      - mesh_net
        #    command: sh -c 'mv tmp/.* . && rmdir tmp'
    command: sh -c 'echo "export PATH=/home/mesh/.local/bin:\$PATH" >> /home/mesh/.bashrc' 
    entrypoint: ["sh", "-c", "sleep 30 && python app/main.py"]

  mmrelayapp:
    build:
      context: .
      dockerfile: Dockerfile_node
    image: mmrelaynode:latest
    container_name: mmrelay-node
    restart: unless-stopped
    user: 1000:1000
    networks:
      - mesh_net
    volumes:
      - mesh_volume:/home/mesh
    ports:
      - 4403:4403
    entrypoint: ["sh", "-cx", "/home/mesh/meshtasticd_linux_amd64 --hwid '1234'"] #change to your own hardware id

networks:
  mesh_net:
volumes:
  mesh_volume:
