version: "3.7"
services:
  mmrelaynode:
    image: mmrelaynode:latest
    container_name: mmrelay-node
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - mesh:/home/mesh
    ports:
      - "4403:4403"
    networks:
      - mesh
    entrypoint: ["sh", "-c", "/usr/bin/meshtasticd -d /home/mesh/node -h 1234"]
#    entrypoint: ["sh", "-c", "/usr/bin/meshtasticd -d /home/mesh/node -h $(grep -Po 'hwid: "\K[^"]+' /home/mesh/app/config.yaml)"]
  mmrelayapp:
    image: mmrelayapp:latest
    container_name: mmrelay-app
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - mesh:/home/mesh
    networks:
      - mesh
    entrypoint: ["sh", "-c", "sleep 30 && python main.py"]

volumes:
  mesh:

networks:
  mesh:
