version: '3.8'

services:
  mmrelaydevice:
    build: device
    image: mmrelaynode:latest
    container_name: mmrelaynode-device
    restart: unless-stopped
    volumes:
      - mesh:/home/mesh
    ports:
      - "4403:4403"
    networks:
      - mesh
    entrypoint: ["sh", "-c", "meshtasticd"]
    environment:
      MESHTASTIC_COMMAND_1: "--set-owner 'LongName' --set-owner-short 'SHRT' --set-url https://meshtastic.org/e/#CgMSAQESDAgBOAFAA0gBUB5oAQ" 
      MESHTASTIC_COMMAND_2: "--set mqtt.enabled true --set mqtt.address mqtt.meshtastic.org --set mqtt.username meshdev --set mqtt.password large4cats"
      # You can add as many MESHTASTIC_COMMAND_X as you need, they will be executed in order with a 30 second delay between or add all your setup in one command.

  mmrelayapp:
    build: app
    image: mmrelayapp:latest
    container_name: mmrelaynode-app
    restart: unless-stopped
    depends_on:
      - mmrelaynode
    volumes:
      - mesh:/home/mesh
    networks:
      - mesh
    entrypoint: [ "sh", "-c", "/home/mesh/.local/bin/wait-for-it.sh mmrelaynode:4403 -t 60 && python3 command_wrapper.py && python3 conf_wrapper.py && python3 main.py" ]
    environment:
      MATRIX_HOMESERVER: "https://example.matrix.org"
      MATRIX_ACCESS_TOKEN: "your_access_token"
      MATRIX_BOT_USER_ID: "@botuser:example.matrix.org"
      MESHTASTIC_CONNECTION_TYPE: "network" # "serial" or "network"
      MESHTASTIC_SERIAL_PORT: "/dev/ttyUSB0"
      MESHTASTIC_HOST: "mmrelaynode"
      MESHTASTIC_MESHNET_NAME: "Your Meshnet Name"
      MESHTASTIC_BROADCAST_ENABLED: "true"
      LOGGING_LEVEL: "info"
      # Need at least 1 room & channel mapped, maximum 8
      MATRIX_ROOMS_ID_1: "#someroomalias1:example.matrix.org"
      MATRIX_ROOMS_MESHTASTIC_CHANNEL_1: "0"
      # MATRIX_ROOMS_ID_2: "#someroomalias2:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_2: "1"
      # MATRIX_ROOMS_ID_3: "#someroomalias3:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_3: "2"
      # MATRIX_ROOMS_ID_4: "#someroomalias4:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_4: "3"
      # MATRIX_ROOMS_ID_5: "#someroomalias5:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_5: "4"
      # MATRIX_ROOMS_ID_6: "#someroomalias6:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_6: "5"
      # MATRIX_ROOMS_ID_7: "#someroomalias7:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_7: "6"
      # MATRIX_ROOMS_ID_8: "#someroomalias8:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_8: "7"
      
      # Plugin environment variables
      # HEALTH_PLUGIN_ACTIVE: "true"
      # MAP_PLUGIN_ACTIVE: "true"
      # NODES_PLUGIN_ACTIVE: "true"

networks:
  mesh:
    driver: bridge

volumes:
  mesh:
