version: '3.8'

services:
  mmrelaynode:
    build: node
    image: mmrelaynode:latest
    container_name: mmrelay-node
    restart: unless-stopped
    volumes:
      - mesh:/home/mesh
    ports:
      - "4403:4403"
    networks:
      - mesh
    entrypoint: ["sh", "-c", "meshtasticd"]

  mmrelayapp:
    build: app
    image: mmrelayapp:latest
    container_name: mmrelay-app
    restart: unless-stopped
    depends_on:
      - mmrelaynode
    volumes:
      - mesh:/home/mesh
    networks:
      - mesh    
    command: ["sh", "-c", "python3 config_wrapper.py && sleep 30 && python3 main.py"]
    environment:
      MATRIX_HOMESERVER: "https://example.matrix.org"
      MATRIX_ACCESS_TOKEN: "your_access_token"
      MATRIX_BOT_USER_ID: "@botuser:example.matrix.org"
      MATRIX_ROOMS_ID_1: "#someroomalias1:example.matrix.org"
      MATRIX_ROOMS_MESHTASTIC_CHANNEL_1: "0"
      # MATRIX_ROOMS_ID_2: "#someroomalias2:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_2: "1"
      # MATRIX_ROOMS_ID_3: "#someroomalias3:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_3: "2"
      # MATRIX_ROOMS_ID_4: "#someroomalias4:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_4: "3"
      # MATRIX_ROOMS_ID_5: "#someroomalias5:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_5: "4"
      # MATRIX_ROOMS_ID_6: "#someroomalias6:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_6: "5"
      # MATRIX_ROOMS_ID_7: "#someroomalias7:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_7: "6"
      # MATRIX_ROOMS_ID_8: "#someroomalias8:example.matrix.org"
      # MATRIX_ROOMS_MESHTASTIC_CHANNEL_8: "7"
      MESHTASTIC_CONNECTION_TYPE: "serial" # "serial" or "network"
      MESHTASTIC_SERIAL_PORT: "/dev/ttyUSB0"
      MESHTASTIC_HOST: "meshtastic.local"
      MESHTASTIC_MESHNET_NAME: "Your Meshnet Name"
      MESHTASTIC_BROADCAST_ENABLED: "true"
      LOGGING_LEVEL: "info"
      # Plugin environment variables (commented out for reference)
      # HEALTH_PLUGIN_ACTIVE: "true"
      # MAP_PLUGIN_ACTIVE: "true"
      # NODES_PLUGIN_ACTIVE: "true"

networks:
  mesh:
    driver: bridge

volumes:
  mesh:
